CASMPET-6799: Add SBPS Marshal Spire Workload on NCN
Cray-HPE/cray-spire pull request #86
Opened 2023-12-12 16:55 UTC by aasha-hpe

sbps-marshal workload needs to be added to spire-server and
      cray-spire-server pods on NCN nodes

## Summary and Scope

sbps-marshal workload which is iSCSI based boot content projection service needs to be added to spire and cray-spire. 

## Testing

Testing is done by adding adding the entries for sbps-marshal workload into spire and cray-spire manually. Detailed steps are in CASMPET-6799. The same needs to be tested using the CSM latest builds once this code is in.

### Tested on:

  * Mug

### Test description:

Testing is done by adding sbps-marshal workload to spire and cray-spire manually. Detailed steps are listed in the CASMPET-6799.

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N/A
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

None.

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable - N/A
- [x] Copyrights updated
- [ ] License file intact - N/A
- [ ] Target branch correct - N/A
- [ ] CHANGELOG.md updated - N/A
- [x] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-02-13 21:42 UTC, jeremy-duckworth requested changes
The workload template in `charts/spire/templates/server/configuration` need to be updated as well. 

@ndavidson-hpe are there any tests that need to be added to cover here?

2024-04-04 17:53 UTC, aasha-hpe commented
> The workload template in `charts/spire/templates/server/configuration` need to be updated as well.
> 
> @ndavidson-hpe are there any tests that need to be added to cover here?



> The workload template in `charts/spire/templates/server/configuration` need to be updated as well.
>
@jeremy-duckworth , Hope you meant charts/cray-spire/templates/server/configuration.yaml and it was updated. Pls let me know if you differ or if am missing anything here. 
 
> @ndavidson-hpe are there any tests that need to be added to cover here?

2024-04-04 19:13 UTC, jeremy-duckworth approved these changes

2024-04-24 17:09 UTC, ndavidson-hpe approved these changes

2024-05-01 19:13 UTC, ndavidson-hpe approved these changes

2024-05-02 20:32 UTC, dborman-hpe commented on charts/cray-spire/templates/server/workloads.yaml
> +      - spiffeID: spiffe://shasta/ncn/workload/sbps-marshal
This should be `{{ .Values.trustDomain }}` instead of hardcoding it to `shasta`

2024-05-02 20:33 UTC, dborman-hpe commented on charts/cray-spire/templates/server/workloads.yaml
> +       - spiffeID: spiffe://shasta/ncn/workload/sbps-marshal
Here too, `shasta` shouldn't be hardcoded, it should be `{{ .Values.trustDomain }}`

2024-05-02 20:35 UTC, dborman-hpe requested changes
Please fix the two instances where `shasta` is hardcoded.

2024-05-03 08:21 UTC, aasha-hpe commented
Thanks David, addressed it.

2024-05-03 14:40 UTC, merged